### ISSUE TITLE
why uesd the batch_size with default =1 ？

### ISSUE THREAD

**Issue by lkf1996** [walsvid/Pixel2MeshPlusPlus#13]
Hi，I have a question why the code uesd 1 as batch_size?   Can I  adjust to others bigger number？
Hope for your reply.  Thanks

**Comment by walsvid** [comment]
The method we use to make ground truth is poisson disk sampling. This method does not guarantee that the number of ground points are consistent, so we use batch size=1. You can use padding to align each batch to increase the batch size.
