### ISSUE TITLE
about the initial template

### ISSUE THREAD

**Issue by fififei** [walsvid/Pixel2MeshPlusPlus#14]
hello!
I have a question about the initial template.
In P2M the mesh is always deformed from the same initial template--Ellipsoid, 
Is it possible to be deformed from different template?

**Comment by walsvid** [comment]
Yes, since we build graph locally, P2M++ can deform from other topology meshes. We have done experiments on voxel->marching cubes->mesh dataset, just replace input initial mesh for MDN.

**Comment by lkf1996** [comment]
> 是的，因为我们在本地构建图形，所以P2M ++可以从其他拓扑网格变形。我们已经在体素->多维数据集->网格数据集上进行了实验，只是将输入的初始网格替换为MDN。

excuse me ？  Can you tell me the meaning of “sample_adj” in pkl[‘sample_cheb_dense’]？ What is the meaning of the matrix ？  Why the Adjacency matrix has negative ？  
Hope for your reply

**Comment by fififei** [comment]
> Yes, since we build graph locally, P2M++ can deform from other topology meshes. We have done experiments on voxel->marching cubes->mesh dataset, just replace input initial mesh for MDN.

thx for your reply!

**Comment by walsvid** [comment]
Hi @lkf1996 `pkl['sample_cheb_dense']` are the laplacian matrix of level1-icosahedron, which is used for chebconv. It is not adjacency matrix, the calculation detail can be found in [chebconv](https://pytorch-geometric.readthedocs.io/en/latest/modules/nn.html#torch_geometric.nn.conv.ChebConv) and [gcn](https://github.com/tkipf/gcn/blob/master/gcn/utils.py#L149).
