### ISSUE TITLE
what‘’s the cm_mat?

### ISSUE THREAD

**Issue by crs904620522** [walsvid/Pixel2MeshPlusPlus#15]
Hello, i think i have a problem when reading the code. what's the "cm_mat" in [../utils/tools.py  cameraMat(param)]? is it the "R"?
but i can't understand it if it's "R".... Could you tell me the method of coordinate transformation in your model?

**Comment by walsvid** [comment]
> Hello, i think i have a problem when reading the code. what's the "cm_mat" in [../utils/tools.py cameraMat(param)]? is it the "R"?
> but i can't understand it if it's "R".... Could you tell me the method of coordinate transformation in your model?

Hi @crs904620522, this function generate R and t using the `yaw roll pitch` angle.  A more comprehensible version is implemented in [there](https://github.com/nywang16/Pixel2Mesh/blob/7c5a7a142d5f64f15250f9e98ee496980f69e005/GenerateData/3_camera_transform.py#L19).  Briefly, we calculate the coordinate when using the camera as the center, based on the camera's position in world coordinate.

**Comment by crs904620522** [comment]
**Thanks**, I will read it carefully, my friend！hhh...
