### ISSUE TITLE
Error when 'make' the Makefile

### ISSUE THREAD

**Issue by tPPMc-cs** [walsvid/Pixel2MeshPlusPlus#26]
I changed the references in the makefile
`nvcc=/usr/local/cuda-10.0/bin/nvcc`
`cudalib=/usr/local/cuda-10.0/lib64`
then make
I got the output:
`make: 放弃循环依赖 tf_approxmatch_g.cu <- tf_approxmatch_g.cu.o 。
g++ -std=c++11 tf_approxmatch.cpp tf_approxmatch_g.cu.o -o tf_approxmatch_so.so -shared -fPIC  -lcudart  -L /usr/local/cuda-10.0/lib64 -O2 -D_GLIBCXX_USE_CXX11_ABI=0
tf_approxmatch.cpp:1:10: fatal error: tensorflow/core/framework/op.h: No such file or directory
 #include "tensorflow/core/framework/op.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:18: recipe for target 'tf_approxmatch_so.so' failed
make: *** [tf_approxmatch_so.so] Error 1
`

I'm confused that where I can set the path to the head file?

**Comment by Stella-Hxy** [comment]
I met a similar problem,could you tell me how did you solve the problem?Thanks!
