### ISSUE TITLE
about support_number=2

### ISSUE THREAD

**Issue by fififei** [walsvid/Pixel2MeshPlusPlus#3]
thanks for sharing! In the train.py file, why you set support_number=2. Is it because of pooling layer, the vertices number increase double?

**Comment by walsvid** [comment]
Hi, `support_number` indicate  the number of expansion terms of Chebyshev polynomial for GCN calculation. Generally speaking, GCN considers each node itself and first-order adjacencies, so it expands 2 terms.

**Comment by fififei** [comment]
Hi walsvid, thanks for your reply!  But I also wondered **support_number=2**, isn't it means second-order neighborhood?

**Comment by walsvid** [comment]
Hi, @fififei  `support_number=1` means only calculate the node itself, `support_number=2` means calculate first-order neighborhood.

**Comment by fififei** [comment]
Hi, @walsvid  I got it. Thanks for your rapid replying !
