### ISSUE TITLE
some touble about NotFoundError

### ISSUE THREAD

**Issue by hzhao1997** [walsvid/Pixel2MeshPlusPlus#6]
hello , I have established the same environment as you , but I run into some troule.

     nn_distance_module = tf.load_op_library('./external/tf_nndistance_so.so')
     lib_handle = py_tf.TF_LoadLibrary(library_filename)

     error:     tensorflow.python.framework.errors_impl.NotFoundError: ./external/tf_nndistance_so.so: undefined symbol: _ZN10tensorflow12OpDefBuilder5InputESs

    The file  named tf_nndistance_so.so does exit, and I try google but I get any useful information.Could you give me a hand ? Thank you!

**Comment by walsvid** [comment]
Hi, @benpaobasaonian12138  The problem is that you need to recompile the `.so` file according to your computer platform. Please use the Makefile I provided and make the necessary modifications, or follow the tutorial I wrote in the **README** on "how to build custom op in tensorflow" to compile the so file step by step.

**Comment by Gocobnus** [comment]
hello，I also encountered this problem,and i modify the Makefile
i change the path of nvcc and  cudalib (nvcc=/usr/local/cuda-9.0/bin/nvcc   cudalib=/usr/local/cuda-9.0/lib64 )
next i I cannot make a .so file after typing ‘make’ in the terminal

tf_nndistance.cpp:1:42: fatal error: tensorflow/core/framework/op.h: No that file or directory
compilation terminated.
Makefile:19: recipe for target 'tf_nndistance_so.so' failed
make: *** [tf_nndistance_so.so] Error 1

looking forward your reply thx^

**Comment by walsvid** [comment]
Hi, @Dacailuanyihao. It seems that the tensorflow you used did not installed in default path, maybe you are using anaconda. After check the path of `tensorflow/core/framework/op.h`, you can add include the path in make file like this: `-I /usr/local/lib/python3.6/dist-packages/tensorflow/include`
