### ISSUE TITLE
Questions about the unpooling layer

### ISSUE THREAD

**Issue by TowerTowerLee** [walsvid/Pixel2MeshPlusPlus#8]
**Hello, thank you for sharing this code！**
I understand the unpooling layer which uesd for adding vertices , but the I have some questions about the code ！

1. In the unpooling layer of the layer.py  , Input are the coordinates of the vertices of the morphed model. I have trouble understanding this code.`add_feat = (1 / 2.0) * tf.reduce_sum(tf.gather(X, self.pool_idx), 1)`Does it finish adding vertices and attribute the feature which is the mean of coordinates of adjacent vertices？
2 Is the unpooling layer output a simply cascade of vertex coordinates of the morphed model and coordinate features of the added vertices?`outputs = tf.concat([X, add_feat], 0)`

**Sorry to bother you, hope to get your answer!**

**Comment by walsvid** [comment]
Hi @TowerTowerLee , `tf.gather` extract feature when given indices, so `add_feat` adding new vertices with the average coordinates and feature of adjacent vertices.
The output of unpooling layer is the old vertices coordinates and old feature + new coordinates and new feature, both new coordinates and new feature are the average of the adjacent old ones.
