### ISSUE TITLE
Camera Parameters

### ISSUE THREAD

**Issue by nitish11** [walsvid/Pixel2MeshPlusPlus#9]
What are the values in the camera parameters? How to define these values for any new test case? For example, if I have 3 images of an object from different view points, how to define camera.txt?

**Comment by walsvid** [comment]
Hi @nitish11 , the camera parameters consists of  numbers, e.g. `222.956664706 28.6626066017 0 0.926673522361 25`. The meaning of each lines in file rendering_metadata.txt: from the left, they are azimuth, elevation, in-plane rotation, distance, the field of view. (in-plane rotation is always zero in ShapeNet dataset. ) For el-az system you can refer to the wiki https://en.wikipedia.org/wiki/Horizontal_coordinate_system.

For training in other data sets, I suggest using a method that can calibrate the extrinsic matrix of the camera such as colmap or other methods. In fact, it is unnecessary to use the el-az system. In our code we using extrinsic (R and t) in the end.
